import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { localPdfPlugin } from "./build/jspdf-local.mjs";

const banner = `/*
This file is generated by esbuild. Do not edit it directly — edit sources in src/ instead.
*/`;

const mode = process.argv[2] ?? "dev";
const prod = mode === "production";

const externalDeps = [
	"obsidian",
	"electron",
	"@electron/remote",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
	...builtins.map((m) => `node:${m}`),
];

const pluginBuild = {
	plugins: [localPdfPlugin()],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: externalDeps,
	format: "cjs",
	platform: "browser",
	target: "es2022",
	logLevel: "info",
	minify: prod,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	banner: { js: banner },
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
};

const harnessBuild = {
	plugins: [localPdfPlugin()],
	entryPoints: ["dev/harness.ts", "dev/bench.ts", "dev/i18n-harness.ts"],
	bundle: true,
	// harness 在浏览器里跑，没有 obsidian / node 运行时，用桩件顶替
	alias: {
		obsidian: "./dev/obsidian-stub.ts",
		fs: "./dev/fs-stub.ts",
		"node:fs": "./dev/fs-stub.ts",
	},
	format: "esm",
	platform: "browser",
	target: "es2022",
	logLevel: "info",
	sourcemap: "inline",
	treeShaking: true,
	outdir: "dev",
	define: {
		"process.env.NODE_ENV": JSON.stringify("development"),
	},
};

if (mode === "harness") {
	await esbuild.build(harnessBuild);
} else if (prod) {
	await esbuild.build(pluginBuild);
} else {
	const ctx = await esbuild.context(pluginBuild);
	await ctx.watch();
}